#Deus & Dan
#18/11/2022
#global reemergence of RSV onset, duration and peak

#====================================================================

#read the WHO RSV update file into R
#source (https://www.who.int/teams/global-influenza-programme/surveillance-and-monitoring/influenza-surveillance-outputs)
rsv <- runIfExpired('who_rsv', maxage = 168, ~read.csv(curl("https://frontdoor-l4uikgap6gz3m.azurefd.net/FLUMART/VIW_FNT?$format=csv")))

#set strings as factors to false globally
options(stringsAsFactors = FALSE)

#get the required variables
rsvds <-
  rsv %>%
  dplyr::filter(!is.na(RSV)) %>%
  dplyr::select(HEMISPHERE, WHOREGION, COUNTRY_AREA_TERRITORY, MMWR_WEEKSTARTDATE, ORIGIN_SOURCE, RSV) %>%
  dplyr::arrange(WHOREGION, COUNTRY_AREA_TERRITORY, MMWR_WEEKSTARTDATE) %>%
  dplyr::rename("hemi" = HEMISPHERE,
                "region" = WHOREGION,
                "country" = COUNTRY_AREA_TERRITORY,
                "date"= MMWR_WEEKSTARTDATE,
                "sentin" = ORIGIN_SOURCE,
                "cases" = RSV)

#view structure of data
str(rsvds)

#expand the dataset to have single case per row
rsvds <- 
  rsvds %>% 
  type.convert(as.is = TRUE) %>% 
  uncount(cases)

#view structure of data
str(rsvds)

#assign data types to variables
rsvds <-
  rsvds %>%
  dplyr::mutate(hemi = factor(hemi),
                region = factor(region),
                country = country,
                date = lubridate::ymd(date),
                sentin = factor(sentin))

# view structure of data
str(rsvds)

#====================================================================
#AFRICAN REGION
#====================================================================
  
#filter to only have these countries included from Africa with somewhat case complete data from 2017
rsv_afr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Central African Republic", "Côte d'Ivoire", "Madagascar", "South Africa"), 
                year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
#combine sentinel and non-sentinel data or use undefined source of RSV cases
rsv_afr <- 
  rsv_afr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), nesting(region, hemi, country), fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_afr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_afr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_afr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  select(everything(), -sentin) %>% 
  full_join(temp_st)

temp_st <- 
  temp_st %>% 
  mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  select(everything(), -cases, -cases2) %>% 
  rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_afr <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_afr %>% 
  janitor::get_dupes(country, date)

rsv_afr <- 
  rsv_afr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================
#SOUTH EAST ASIAN REGION
#====================================================================

#filter to only have these countries included from South East Asia with somewhat case complete data from 2017
rsv_sear <- 
  rsvds %>%
  dplyr::filter(country %in% c("India"), 
                year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
#combine sentinel and non-sentinel data or use undefined source of RSV cases
rsv_sear <- 
  rsv_sear %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), nesting(region, hemi, country), fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_sear %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_sear %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_sear %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  select(everything(), -sentin) %>% 
  full_join(temp_st)

temp_st <- 
  temp_st %>% 
  mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  select(everything(), -cases, -cases2) %>% 
  rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_sear <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                       temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_sear %>% 
  janitor::get_dupes(country, date)

rsv_sear <- 
  rsv_sear %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================
#WESTERN PACIFIC REGION
#====================================================================

#filter to only have these countries included from Westeen Pacific with somewhat case complete data from 2017
rsv_wpr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Australia", "Japan", "Mongolia", "Malaysia"), 
                year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_wpr <- 
  rsv_wpr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), nesting(region, hemi, country), fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_wpr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_wpr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_wpr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  select(everything(), -sentin) %>% 
  full_join(temp_st)

temp_st <- 
  temp_st %>% 
  mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  select(everything(), -cases, -cases2) %>% 
  rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_wpr <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_wpr %>% 
  janitor::get_dupes(country, date)

rsv_wpr <- 
  rsv_wpr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================
#EASTERN MEDITERRANEAN REGION
#====================================================================

#filter to only have these countries included from Eastern Mediterranean with somewhat case complete data from 2017
rsv_emr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Oman", "Qatar"), 
                year(date) >= 2017)

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_emr <- 
  rsv_emr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), nesting(region, hemi, country), fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_emr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_emr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_emr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  select(everything(), -sentin) %>% 
  full_join(temp_st)

temp_st <- 
  temp_st %>% 
  mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  select(everything(), -cases, -cases2) %>% 
  rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_emr <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                       temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_emr %>% 
  janitor::get_dupes(country, date)

rsv_emr <- 
  rsv_emr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================
#EUROPEAN REGION
#====================================================================

#filter to only have these countries included from Europe with somewhat case complete data from 2017
rsv_euro <- 
  rsvds %>%
  dplyr::filter(country %in% c("France", "Germany", "Netherlands", "Spain", "Portugal", "Iceland",
                               "Ireland", "Denmark", "Sweden", "United Kingdom, England", 
                               "United Kingdom, Northern Ireland", "United Kingdom, Scotland",
                               "Bulgaria", "Hungary", "Slovakia"), 
                year(date) >= 2017) %>%
  dplyr::mutate(country = if_else(country == "United Kingdom, Northern Ireland", "Northern Ireland",
                                  if_else(country == "United Kingdom, Scotland", "Scotland",
                                          if_else(country == "United Kingdom, England", "England", country))))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_euro <- 
  rsv_euro %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), nesting(region, hemi, country), fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_euro %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_euro %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_euro %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  select(everything(), -sentin) %>% 
  full_join(temp_st)

temp_st <- 
  temp_st %>% 
  mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  select(everything(), -cases, -cases2) %>% 
  rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_euro <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_euro %>% 
  janitor::get_dupes(country, date)

rsv_euro <- 
  rsv_euro %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================
#AMERICAS REGION
#====================================================================

#filter to only have these countries included from Americas with somewhat case complete data from 2017
rsv_amer <- 
  rsvds %>%
  dplyr::filter(country %in% c("Argentina", "Belize", "Bolivia (Plurinational State of)", "Brazil", "Canada", "Colombia", "Costa Rica",
                               "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Honduras", "Mexico",
                               "Nicaragua", "Panama", "Paraguay", "Peru", "Uruguay"),
                year(date) >= 2017) %>%
  dplyr:: mutate(country = if_else(country == "Bolivia (Plurinational State of)", "Bolivia",
                                   if_else(country == "Dominican Republic", "Dominica", country)))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_amer <- 
  rsv_amer %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), nesting(region, hemi, country), fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_amer %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_amer %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_amer %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  select(everything(), -sentin) %>% 
  full_join(temp_st)

temp_st <- 
  temp_st %>% 
  mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  select(everything(), -cases, -cases2) %>% 
  rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_amer <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_amer %>% 
  janitor::get_dupes(country, date)

rsv_amer <- 
  rsv_amer %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================
#====================================================================

#combine all the datasets for hemisphere and regional RSV seasonal dynamics plotting
rsv_all <- 
  rsv_afr %>% 
  dplyr::bind_rows(rsv_sear) %>%
  dplyr::bind_rows(rsv_wpr) %>%
  dplyr::bind_rows(rsv_emr) %>%
  dplyr::bind_rows(rsv_euro) %>%
  dplyr::bind_rows(rsv_amer) %>%
  mutate(region = if_else(region == "AFR", "Africa",
                          if_else(region == "AMR", "Americas",
                                  if_else(region == "EMR", "Eastern Mediterranean",
                                          if_else(region == "EUR", "Europe",
                                                  if_else(region == "SEAR", "South East Asia", "Western Pacific"))))),
         hemi = if_else(hemi == "SH", "Southern hemisphere", "Northern hemisphere"))
