#Authors: Deus & Dan
#Date: 01/03/2023
#Title: Rebound to normal RSV dynamics post COVID-19 suppression

#====================================================================
# WORLD HEALTH ORGANISATION DATA (VIA FLUNET)
#====================================================================

#read the WHO RSV update file into R
#source (https://www.who.int/teams/global-influenza-programme/surveillance-and-monitoring/influenza-surveillance-outputs)
rsv <- runIfExpired('who_rsv', maxage = 168, ~read.csv(curl("https://frontdoor-l4uikgap6gz3m.azurefd.net/FLUMART/VIW_FNT?$format=csv")))
#rsv <- rio::import(here("data", "alter_rsv", "VIW_FNT.csv")) #alternative way to input update rsv data if the link above is not working

#set strings as factors to false globally
base::options(stringsAsFactors = FALSE)

#get the required variables
rsvds <-
  rsv %>%
  dplyr::filter(!is.na(RSV)) %>%
  dplyr::select(HEMISPHERE, WHOREGION, COUNTRY_AREA_TERRITORY, MMWR_WEEKSTARTDATE, ORIGIN_SOURCE, RSV) %>%
  dplyr::rename("hemi" = HEMISPHERE,
                "region" = WHOREGION,
                "country" = COUNTRY_AREA_TERRITORY,
                "date"= MMWR_WEEKSTARTDATE,
                "sentin" = ORIGIN_SOURCE,
                "cases" = RSV)

#view structure of data
utils::str(rsvds)

#expand the dataset to have single case per row
rsvds <- 
  rsvds %>% 
  dplyr::arrange(hemi, region, country, date, sentin) %>%
  utils::type.convert(as.is = TRUE) %>% 
  tidyr::uncount(cases)

#view structure of data
utils::str(rsvds)

#assign data types to variables
rsvds <-
  rsvds %>%
  dplyr::mutate(hemi = factor(hemi),
                region = factor(region),
                country = country,
                date = lubridate::ymd(date),
                sentin = factor(sentin))

# view structure of data
utils::str(rsvds)

#====================================================================
  
#filter to only have these countries included from Africa with somewhat case complete data from 2017
rsv_afr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Central African Republic", "Côte d’Ivoire", "Madagascar", "South Africa"), year(date) >= 2017) %>% # Cameroon, Uganda
  dplyr::mutate(country = if_else(country == "Côte d’Ivoire", "Ivory Coast", country)) 

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
#combine sentinel and non-sentinel data or use undefined source of RSV cases
rsv_afr <- 
  rsv_afr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(hemi, region, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_afr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_afr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_afr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_afr <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_afr %>% 
  janitor::get_dupes(country, date)

rsv_afr <- 
  rsv_afr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from South East Asia with somewhat case complete data from 2017
rsv_sear <- 
  rsvds %>%
  dplyr::filter(country %in% c("India"), year(date) >= 2017) #Timor-Leste, India, Thailand

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
#combine sentinel and non-sentinel data or use undefined source of RSV cases
rsv_sear <- 
  rsv_sear %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_sear %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_sear %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_sear %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_sear <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                       temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_sear %>% 
  janitor::get_dupes(country, date)

rsv_sear <- 
  rsv_sear %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from Western Pacific with somewhat case complete data from 2017
rsv_wpr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Australia", "Japan", "Mongolia", "Malaysia"), year(date) >= 2017) #China Hong Kong SAR, Australia, Japan, Mongolia, Malaysia, Republic of Korea

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_wpr <- 
  rsv_wpr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_wpr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_wpr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_wpr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_wpr <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_wpr %>% 
  janitor::get_dupes(country, date)

rsv_wpr <- 
  rsv_wpr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from Eastern Mediterranean with somewhat case complete data from 2017
rsv_emr <- 
  rsvds %>%
  dplyr::filter(country %in% c("Oman", "Qatar"), year(date) >= 2017) #Qatar, Oman, United Arab Emirates, Kuwait

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_emr <- 
  rsv_emr %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_emr %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_emr %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_emr %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_emr <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                       temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_emr %>% 
  janitor::get_dupes(country, date)

rsv_emr <- 
  rsv_emr %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)


#====================================================================

#filter to only have these countries included from Europe with somewhat case complete data from 2017
rsv_euro <- 
  rsvds %>%
  dplyr::filter(country %in% c("France", "Germany", "Netherlands", "Netherlands (Kingdom of the)", "Spain", "Portugal", "Iceland",
                               "Ireland", "Denmark", "Sweden", "United Kingdom, England", 
                               "United Kingdom, Northern Ireland", "United Kingdom, Scotland",
                               "Bulgaria", "Hungary", "Slovakia"), year(date) >= 2017) %>%
  dplyr::mutate(country = if_else(country == "United Kingdom, Northern Ireland", "Northern Ireland",
                                  if_else(country == "United Kingdom, Scotland", "Scotland",
                                          if_else(country == "United Kingdom, England", "England",
                                                  if_else(country == "Netherlands (Kingdom of the)", "Netherlands", country)))))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_euro <- 
  rsv_euro %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_euro %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_euro %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_euro %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases, na.rm = TRUE)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_euro <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_euro %>% 
  janitor::get_dupes(country, date)

rsv_euro <- 
  rsv_euro %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#filter to only have these countries included from Americas with somewhat case complete data from 2017
rsv_amer <- 
  rsvds %>%
  dplyr::filter(country %in% c("Argentina", "Belize", "Bolivia (Plurinational State of)", "Brazil", "Canada", "Colombia", "Costa Rica",
                               "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Honduras", "Mexico",
                               "Nicaragua", "Panama", "Paraguay", "Peru", "Uruguay"), year(date) >= 2017) %>%
  dplyr:: mutate(country = if_else(country == "Bolivia (Plurinational State of)", "Bolivia",
                                   if_else(country == "Dominican Republic", "Dominica", country)))

#'Not defined' may include sentinel or non-sentinel data
#'properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_amer <- 
  rsv_amer %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, sentin, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>% 
  dplyr::count(wkcases) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(country, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"), 
                  nesting(region, hemi, country), 
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, sentin, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#separate datasets by source of cases
temp_ms <- rsv_amer %>% dplyr::filter(is.na(sentin)) #dataset with missing source (generated by zero cases for weekly reporting)
temp_nd <- rsv_amer %>% dplyr::filter(sentin == "NOTDEFINED") #dataset with NOT DEFINED source
temp_st <- rsv_amer %>% dplyr::filter(sentin == "NONSENTINEL" | sentin == "SENTINEL") #dataset with sentinel and non-sentinel source

#combine sentinel and non-sentinel data
temp_st <- temp_st %>%
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>%
  dplyr::summarise(cases2 = sum(cases)) %>%
  dplyr::ungroup()

#choose between "not defined" and "sentinel" reporting depnding on which has most cases
temp_st <- 
  temp_nd %>% 
  dplyr::select(everything(), -sentin) %>% 
  dplyr::full_join(temp_st)

temp_st <- 
  temp_st %>% 
  dplyr::mutate(cases3 = if_else(!is.na(cases) & !is.na(cases2) & cases > cases2, cases,
                          if_else(!is.na(cases) & !is.na(cases2) & cases2 > cases, cases2,
                                  if_else(is.na(cases) & !is.na(cases2), cases2, cases)))) %>%
  dplyr::select(everything(), -cases, -cases2) %>% 
  dplyr::rename("cases" = "cases3")

#now merge with 0 source of RSV cases (generated by zero cases for weekly reporting)
rsv_amer <- rows_append(temp_ms %>% select(hemi, region, country, date, yr, mo, wk, cases), 
                        temp_st %>% select(hemi, region, country, date, yr, mo, wk, cases))

#check for duplicates by country and date
rsv_amer %>% 
  janitor::get_dupes(country, date)

rsv_amer <- 
  rsv_amer %>% 
  dplyr::distinct(country, date, .keep_all = TRUE)

#====================================================================

#combine all the global datasets
rsv_who <- 
  rsv_afr %>% 
  dplyr::bind_rows(rsv_sear) %>%
  dplyr::bind_rows(rsv_wpr) %>%
  dplyr::bind_rows(rsv_emr) %>%
  dplyr::bind_rows(rsv_euro) %>%
  dplyr::bind_rows(rsv_amer) %>%
  mutate(region = if_else(region == "AFR", "Africa",
                          if_else(region == "AMR", "Americas",
                                  if_else(region == "EMR", "Eastern Mediterranean",
                                          if_else(region == "EUR", "Europe",
                                                  if_else(region == "SEAR", "South East Asia", "Western Pacific"))))),
         hemi = if_else(hemi == "SH", "Southern hemisphere", "Northern hemisphere"))

#====================================================================
# UNITED STATES DATA
#====================================================================

#read the CDC RSV update file/dataset into R, both case detection and testing (US regional data from 2021 onwards)
rsv_usa_reg1 <- 
  rio::import('https://data.cdc.gov/resource/3cxc-4k8q.json?$limit=200000') %>%
  dplyr::select(level, pcr_percent_positive, pcr_detections, pcr_tests, mmwrweek_end) %>%
  dplyr::filter(level != "National") %>%
  dplyr::rename("date" = "mmwrweek_end") %>%
  dplyr::mutate(hemi = "Northern hemisphere",
                region = "Americas",
                country = "United States",
                regionUS = if_else(level == "Region 1" | level == "Region 2", "United States North East", #collapse HHS regions into census regions
                                   if_else(level == "Region 3" | level == "Region 4" | level == "Region 6", "United States South",
                                           if_else(level == "Region 5" | level == "Region 7", "United States Mid West", "United States West"))),
                cases = as.numeric(pcr_tests) * as.numeric(pcr_percent_positive)/100,
                date = ymd(str_sub(date, 1, 10)),
                cases = round(cases, digits = 0)) %>%
  dplyr::filter(date >= date('2020-07-04')) %>%
  dplyr::select(hemi, region, country, regionUS, date, cases) %>%
  dplyr::group_by(hemi, region, country, regionUS, date) %>%
  dplyr::summarise(cases = mean(cases)) %>%
  dplyr::ungroup()

#view structure of data
utils::str(rsv_usa_reg1)

#====================================================================

#read the CDC RSV update file/dataset into R (US regional data from 2020 backwards)
#source (https://healthdata.gov/dataset/Respiratory-Syncytial-Virus-Laboratory-Data-NREVSS/7zgq-bp9w)
rsv_usa_reg2 <- 
  runIfExpired('usa_rsv/rsv2020-', maxage = 168, ~read.csv(curl("https://data.cdc.gov/api/views/52kb-ccu2/rows.csv?accessType=DOWNLOAD"))) %>%
  dplyr::filter(!is.na(RSV.Detections)) %>%
  dplyr::select(Week.ending.Date, HHS.region, RSV.Detections) %>%
  dplyr::mutate(hemi = "Northern hemisphere",
                region = "Americas",
                country = "United States",
                Week.ending.Date = lubridate::dmy(Week.ending.Date),
                regionUS = if_else(HHS.region == 1 | HHS.region == 2, "United States North East", #collapse HHS regions into census regions (as only census regional data are scrappable post 2020)
                                   if_else(HHS.region == 3 | HHS.region == 4 | HHS.region == 6, "United States South",
                                           if_else(HHS.region == 5 | HHS.region == 7, "United States Mid West", "United States West")))) %>%
  dplyr::rename("date"= Week.ending.Date,
                "cases" = RSV.Detections) %>%
  dplyr::select(hemi, region, country, regionUS, date, cases) %>%
  dplyr::group_by(hemi, region, country, regionUS, date) %>%
  dplyr::summarise(cases = sum(cases)) %>%
  dplyr::ungroup()

#view structure of data
utils::str(rsv_usa_reg2)

#====================================================================

#combine dataset from 2020 backwards (rsv_usa2) and 2021 onwards (rsv_usa1)
rsv_usa_reg <-
  dplyr::rows_append(rsv_usa_reg1, rsv_usa_reg2) %>%
  dplyr::mutate(cases = round(cases, digits = 0))

#expand
rsv_usa_reg <-
  rsv_usa_reg %>% 
  utils::type.convert(as.is = TRUE) %>% 
  tidyr:: uncount(cases)

#assign data types
rsv_usa_reg <-
  rsv_usa_reg %>%
  dplyr::mutate(hemi = factor(hemi),
                region = factor(region),
                country = country,
                regionUS = regionUS,
                date = lubridate::ymd(date))

#view structure of data
utils::str(rsv_usa_reg)

#properly index by week to have 0 or some observed number of cases in sequential weeks
rsv_usa_reg <- 
  rsv_usa_reg %>% 
  tidyr::drop_na(date) %>%
  dplyr::group_by(region, hemi, country, regionUS, date) %>%
  dplyr::mutate(wkcases = floor_date(date, unit = "week")) %>%
  dplyr::count(wkcases) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(country, regionUS, date) %>%
  tidyr::complete(wkcases = seq.Date(from = min(wkcases), to = max(wkcases), by = "week"),
                  nesting(region, hemi, country, regionUS),
                  fill = list(n = 0L)) %>%
  dplyr::select(hemi, region, country, regionUS, wkcases, n) %>%
  dplyr::rename("date" = "wkcases", "cases" = "n") %>%
  dplyr::mutate(yr = lubridate::year(date),
                mo = lubridate::month(date),
                wk = lubridate::week(date))

#check for duplicates by country and date
rsv_usa_reg %>% 
  janitor::get_dupes(regionUS, date)

rsv_usa_reg <- 
  rsv_usa_reg %>% 
  dplyr::filter(yr >= 2017) %>%
  dplyr::distinct(regionUS, date, .keep_all = TRUE) %>%
  dplyr::select(hemi, region, country, date, cases, yr, mo, wk, regionUS)

#====================================================================

#combine regional datasets to make national then combine with each region in single dataset
rsv_usa <-
  rsv_usa_reg %>% 
  dplyr::select(everything(), -regionUS) %>% 
  dplyr::group_by(hemi, region, country, date, yr, mo, wk) %>% 
  dplyr::summarise(cases = sum(cases, na.rm = TRUE)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(regionUS = "United States") %>%
  dplyr::select(hemi:date,  yr, mo, wk, regionUS, cases) %>%
  dplyr::rows_append(rsv_usa_reg)

#====================================================================
#====================================================================

#combine USA data and global data
rsv_all <-
bind_rows(
  rsv_usa %>% 
    plyr::mutate(country = regionUS) %>%
    select(hemi:date, yr:wk, cases),
  rsv_who
)

#separate north and south Americas
rsv_all <- 
rsv_all %>%
  mutate(region = if_else(country %in% c("Argentina", "Belize", "Bolivia", "Brazil", "Colombia", "Costa Rica", "Dominica", "Ecuador", "El Salvador", 
                                         "Guatemala", "Honduras", "Nicaragua", "Panama", "Paraguay", "Peru", "Uruguay"), "South Americas",
                          if_else(country %in% c("Canada", "Mexico", "United States", "United States Mid West", "United States North East", 
                                                 "United States South", "United States West"), "North Americas", region)))

# #set southern hemisphere countries to start from 1st week of 2017 to 52th week of 2022
# south <- rsv_all %>% dplyr::filter(hemi == "Southern hemisphere" & date >= date("2017-01-08"))
# 
# #set northern hemisphere countries to start from 24th week of 2017 to 23rd week of 2023
# north <- rsv_all %>% dplyr::filter(hemi == "Northern hemisphere" & date >= date("2017-06-11"))
# 
# #now combine the datasets
# rsv_all <- bind_rows(south, north)

#delete all temporary datasets
rm(list = grep("rsv_all", ls(), value = TRUE, invert = TRUE))

#filter to date you want
rsv_all <-
  rsv_all %>%
  dplyr::filter(date(date) <= "2024-06-30")

#====================================================================
#CLIMATE RELATED DATA
#====================================================================

#import climate data that assign each country to temperate or tropical for easy weekly scaling
climate <-
import(here("data", "climate", "climate.csv"))
